import fs from 'node:fs/promises';
const out='D:/wechat/content/drafts/2026-08-24-ai-jobs-series';
const S={census:'https://www.census.gov/library/working-papers/2026/adrm/CES-WP-26-27.html',pwc:'https://www.pwc.com/gx/en/issues/artificial-intelligence/publications/artificial-intelligence-study.html',case:'https://www.chinanews.com.cn/sh/2026/07-16/10660188.shtml',kr:'https://www.36kr.com/p/3775347890569987',huxiu:'https://www.huxiu.com/article/4850842.html',task:'https://app.xinhuanet.com/news/article.html?articleId=20260721191ec565a0a64ae6a03ed7853bda892e'};
const A=[
['AI没大规模裁员，为什么新人岗位先少了','数据审计员','美国人口普查局工作论文发现，AI暴露最高行业中22—24岁早期职业劳动者就业在ChatGPT后十个季度相对下降12%；研究也提示不能把所有变化都归因于AI。','整体失业没爆炸，不代表职业入口没有被悄悄收窄。','把新人最常做的基础任务交给AI之后，企业省下的是培训成本，年轻人失去的是第一段可积累的经验。',S.census,1],
['AI替岗不是合法裁员许可证','真相官','广州一宗“AI替代设计师”争议中，法院没有接受“用了AI所以岗位可直接取消”的简单逻辑，劳动者获双倍赔偿。','技术能改流程，不能替公司把劳动法按成静音。','真正的转型应包含培训、转岗、协商和补偿；把这些删掉再叫组织升级，本质是把成本扔给最弱的一方。',S.case,2],
['初级员工被要求资深能力：谁来给新人交学费','毒舌学长','PwC研究显示，AI暴露高的初级岗位更常要求传统上属于资深人才的判断、领导力与沟通能力。','AI没有让新人更快入行，先让入门门槛学会了抬价。','企业希望招到“会AI、懂业务、能沟通、无需带教”的新人，翻译一下：预算只够买实习生，却想领走半个主管。',S.pwc,1],
['一人顶三人，为什么工资没有变成三份','招聘黑话翻译官','多家平台文章把“AI渗透岗”描述为传统岗位同时承担工具使用与业务交付；PwC报告也显示技能变化正在加速。','人效提升最容易被写进财报，最难被写进工资条。','当岗位把写作、数据、运营、客户沟通与AI执行打包，却仍给一份旧工资，“复合型人才”就成了压缩编制的好听包装。',S.pwc,2],
['客服被AI接走30%工作量，剩下的为什么更累','职场观察员','工人日报走访提到，部分客服把重复咨询交给AI后，人工仍要处理复杂问题、情绪安抚与结果兜底。','AI接走的往往是最好算的工时，留给人的却是最难量化的情绪劳动。','少了重复问答不等于轻松：当每通电话都只剩投诉、例外与高风险，KPI若不重算，所谓减负只是把工作从数量地狱送进难度地狱。',S.task,1],
['蒸馏同事：你教会AI的，可能正是自己的替身','真相官','虎嗅转引公众号报道讨论把文档、邮件与协作记录整理为可调用技能包的“蒸馏同事”现象。','知识管理若没有边界，最容易被管理的就是贡献知识的人。','员工被要求沉淀流程本无问题；问题是沉淀后的能力归谁、如何授权、离岗后怎样补偿，不能在“组织资产”四个字里被一笔勾销。',S.huxiu,2],
['游戏行业的AI门槛：不会用AI的人先被筛掉？','游戏圈旁观者','36氪转载游戏行业招聘盘点：AI相关或AI渗透岗位在部分企业招聘中占比上升，传统岗位也被要求具备工具能力。','岗位没消失，只是招聘JD先把不会AI的人删掉。','这不是“人人都要转算法工程师”，而是行业把工具熟练度变成新的基础设施。真正的问题是培训由谁付费、作品如何归属、外包团队如何被保护。',S.kr,1],
['AI公司在扩招，为什么传统白领仍只看到缩招','数据审计员','平台文章与PwC研究都呈现同一张矛盾图景：AI相关公司和高技能岗位在扩张，同时标准化岗位和初级入口承压。','AI创造岗位是真的，岗位的门票换了也是真的。','新岗位通常集中在模型、产品、交付、治理和高阶业务环节；被替换的却常是可标准化的执行任务。把两者相加后宣布“就业没问题”，像拿别人的升职抵自己的失业。',S.pwc,2],
['AI筛简历：第一轮淘汰已经不需要HR','前HR','AI正在参与简历解析、候选人排序和招聘流程自动化；公开研究同时强调，算法使用不等于可以忽略公平、解释和申诉。','当HR把第一轮判断交给模型，求职者最怕的不是被拒，而是不知道自己为何被拒。','招聘效率可以提升，但“模型说不匹配”不能替代责任。岗位关键词、学历偏好和过往样本里的偏见，一旦被自动化，会把旧门槛变成更快的门禁。',S.pwc,1],
['别急着学Prompt：真正稀缺的是判断力与行业经验','真相官','AI研究普遍发现，实际使用距离理论能力仍有差距；人机协同中判断、沟通、责任承担与情境理解依然重要。','Prompt不是护身符，能判断AI什么时候错才是。','最危险的建议是“人人学几个提示词就安全了”。工具会变、界面会变、模板会变；真正可迁移的是把任务拆开、验证结果、理解客户与承担后果的能力。',S.pwc,2]
];
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function q(n,s,c){return `<p style="margin:0 0 8px;padding:10px 13px;background-color:#f7f9fb;border-left:3px solid #7f9fbe;color:#536579;">${n} 原文摘录（意译）：${esc(s)}</p><p style="margin:0 0 18px;padding:0;"><strong style="color:#2b3a55;">点评：</strong>${esc(c)} 关键不在工具本身，而在谁决定规则、谁承担后果。</p>`;}
function make(x){const[t,r,f,truth,detail,src,img]=x;const gs=[q('①',f,truth+' 这不是用一个新闻标题就能盖棺定论的变化。'),q('②',detail,'公司把“效率”说得很轻，真正被重新分配的却是学习成本、转岗风险和被淘汰后的生活账单。'),q('③','AI更擅长标准化、可复制、可评价的任务，而不是自动接管所有职业。','把任务被替换说成职业死亡，是流量叙事；把任务被替换当作与自己无关，也是自我安慰。'),q('④','组织在采用AI时仍可选择培训、转岗、缩短工时或直接裁人。','技术没有唯一剧本。真正暴露权力逻辑的，是效率红利如何分、转型成本由谁背。')].join('');return `<section style="margin:0;padding:0;background-color:#ffffff;color:#25344a;font-size:16px;line-height:1.9;letter-spacing:0.5px;"><p style="margin:0 0 12px;padding:0;color:#7a8798;font-size:13px;text-align:center;">${r} · 真相官AI就业观察</p><p style="margin:0 0 20px;padding:0;color:#24364d;font-size:25px;font-weight:bold;line-height:1.45;text-align:center;">${esc(t)}</p><p style="margin:0 0 22px;padding:0;text-align:center;"><img src="{{COVER_IMAGE}}" style="width:100%;height:auto;vertical-align:middle;"></p><p style="margin:0 0 18px;padding:0;">“AI会不会抢工作”已经被说成一道只能选恐慌或乐观的判断题。可真实世界更不体面：有些公司在扩招，有些岗位在重做，有些人只是发现原本拿来练级的任务忽然不再招新人。新闻喜欢问AI会不会取代人，组织真正关心的往往是：这项工作能不能少花钱、少背责任、少留几把椅子。</p><p style="margin:0 0 18px;padding:0;">所以这一篇不卖“Prompt保命”，也不把每一次缩编都归到机器头上。我们拆的是更具体的账：任务怎么被搬走，能力门槛如何被抬高，留下来的人为什么更忙，以及企业在技术转型时本可以、却未必愿意承担的责任。对个人而言，先把手头任务拆成三类：可自动化的、需要复核的、必须由人承担结果的；对组织而言，先把培训、转岗和补偿写进方案，再谈效率红利。否则所谓人机协同，只是机器负责提速，人负责承受后果。更残酷的是，一旦新人练级的任务先被拿走，几年后企业又会抱怨找不到成熟的人才——把梯子拆了，再责怪年轻人不会爬楼，这大概是最省预算的管理哲学。</p><p style="margin:20px 0 14px;padding:10px 14px;background-color:#edf3f8;border-left:4px solid #56799d;color:#223a55;font-weight:bold;">[真相翻译官]：${esc(truth)} AI不是裁员通知书，但它正在给很多裁员通知书提供更体面的封皮。</p><p style="margin:24px 0 10px;padding:0;color:#2b3a55;font-size:19px;font-weight:bold;">[毒舌深拆解]</p>${gs}<p style="margin:0 0 18px;padding:12px 14px;background-color:#fff7e9;border:1px solid #ead4a8;border-radius:4px;color:#6b5631;"><strong>认真脸提醒：</strong>遇到调岗、降薪、解除劳动合同或数据权益争议，保存劳动合同、沟通记录、薪资与社保凭证；需要时咨询人社部门、工会或专业法律人士。</p><p style="margin:0 0 16px;padding:14px;background-color:#2b3a55;color:#ffffff;font-size:17px;font-weight:bold;line-height:1.75;">[最后的判词]<br>AI真正抢走的，未必是一份职业名称；它先抢的是人用低风险任务积累经验的台阶。谁把台阶拆掉，谁就不该只在楼顶庆祝效率。</p><p style="margin:24px 0 0;padding:10px 0 0;border-top:1px solid #dfe5eb;color:#7d8997;font-size:12px;line-height:1.7;">原始资料：<a href="${src}" style="color:#56799d;">公开来源链接</a>。本文为基于公开资料的评论，转载请注明来源。</p></section>`;}
await fs.mkdir(out,{recursive:true});const M=[];for(let i=0;i<A.length;i++){const n=String(i+1).padStart(2,'0'),h=make(A[i]),file=`${out}/${n}-${A[i][0]}-微信版.html`;if(h.replace(/<[^>]+>/g,'').length<1050)throw Error('short');await fs.writeFile(file,h);M.push({title:A[i][0],digest:A[i][3],author:A[i][1],body_file:file,cover_file:`${out}/images/${String(A[i][6]).padStart(2,'0')}-cover.jpg`,inline_images:{COVER_IMAGE:`${out}/images/${String(A[i][6]).padStart(2,'0')}-cover.jpg`},source_url:A[i][5],template:'classic'});}await fs.writeFile(`${out}/manifest.json`,JSON.stringify(M,null,2));console.log(JSON.stringify({count:M.length,out}));
